env:
  - DB_USERNAME=root
  - DB_URL=jdbc:mysql://127.0.0.1/test;
  - DB_PASSWORD=

before_install:
    - "mysql -e 'create database if not exists test;'"
    - export DB_PASSWORD=

language: groovy

script:
    - mvn -q clean verify

branches:
  only:
    - master