# .travis.yml
before_script:
  - "mysql -e 'create database myapp_test;'"

language: groovy

env:
  - DB_USERNAME=root DB_URL=jdbc:mysql://127.0.0.1/myapp_test; DB_PASSWORD=

script: mvn -q clean verify

branches:
  only:
    - master