language: java

env:
  - DB_USERNAME=root DB_URL=jdbc:mysql://127.0.0.1/test DB=mysql;

#Travis install phase executes mvn test, which fires the mvn sql plugin execution.
#You need a database created before the Travis install phase (see the before_install below).
#Be aware that by default, travis seems to use a username of vagrant that is not an admin on the database and cant grant permission.
#Override this by specifying the user/password when executing a command. Don't use the shortened password -p command.

before_install:
    - mysql --user=root --password= -e 'create database if not exists test;'

script:
    - mvn -q clean verify

branches:
  only:
    - master