env:
  - DB_USERNAME=user DB_PASSWORD=password DB_URL=jdbc:mysql://127.0.0.1/test;

#install phase executes mvn test, which fires the mvn sql plugin execution, so you need a database created.
before_install:
    - mysql --user=root --password= -e 'create database if not exists test;'
    - mysql --user=root --password= -e "CREATE USER 'user'@'%' IDENTIFIED BY 'password';"
    - mysql --user=root --password= -e 'select User from mysql.user;'
    - mysql --user=root --password= -e "grant all on test.* to 'user'@'%' identified by 'password';"



language: groovy

script:
    - mvn -q clean verify

branches:
  only:
    - master