language: groovy

before_script:
  - mysql -e 'create database test;'

env:
  - DB_USERNAME=root DB_URL=jdbc:mysql://127.0.0.1/test DB_PASSWORD=

script: mvn -q clean verify

branches:
  only:
    - master