env:
  - DB_USERNAME=user DB_PASSWORD=password DB_URL=jdbc:mysql://127.0.0.1/test;

#install phase executes mvn test, which fires the mvn sql plugin execution, so you need a database created.
before_install:
    - mysql -e 'create database if not exists test;'
    - mysql -e "CREATE USER 'user'@'%' IDENTIFIED BY 'password';"
    - mysql -e 'select User from mysql.user;'
    - mysql -e '-u root -p test;'
    - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;"

language: groovy

script:
    - mvn -q clean verify

branches:
  only:
    - master