env:
  - DB_USERNAME=user DB_PASSWORD=password DB_URL=jdbc:mysql://127.0.0.1/test;

before_install:
    - mysql -e 'create database if not exists test;'
    - mysql -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';"

language: groovy

script:
    - mvn -q clean verify

branches:
  only:
    - master