before_script:
  - "mysql -e 'create database if not exists test;'"

language: groovy

env:
  - DB_USERNAME=root DB_URL=jdbc:mysql://127.0.0.1/test; DB_PASSWORD=

script:
script:
    - env | grep DB_USERNAME
    - mysql --user=root --password=
    - mysql show databases;
    - mvn -q clean verify

branches:
  only:
    - master